### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by Midhil457** [arthuro555/gdmod#22]
Hi, a while ago, when I was looking for something to do, I took GDMod as an inspiration and made a logo for it. I forgot about it and I recently found it and thought you might like it :)

![GDFull](https://user-images.githubusercontent.com/73597906/126038425-21506fb4-f407-4a5a-9088-e42cc6c4df55.png)

Symbol/icon:
![GDSymbol](https://user-images.githubusercontent.com/73597906/126038459-6d2578d7-49eb-4185-9fb5-3376338ee812.png)

The meaning:

![GdMeaning](https://user-images.githubusercontent.com/73597906/126038443-e717a347-ca6c-4c18-beba-33f843a9fd28.png)

More: 
[GDmod.zip](https://github.com/arthuro555/gdmod/files/6834757/GDmod.zip)

:)

**Comment by arthuro555** [comment]
Wow, this looks so good, thanks! Would you be ok with me using it as the official logo for the project?

**Comment by Midhil457** [comment]
Yes, feel free to use it in anyway you like :)

I have included the SVGs, PNGs, and all other things here: 
[GDmod.zip](https://github.com/arthuro555/gdmod/files/6835789/GDmod.zip)

:)
